In [1]:
import os
import pandas as pd
import numpy as np 
import pickle
import scipy.io


In [2]:
all_data = list()
root_de_data = 'raw_data/Large_affective/EEG_Features/DE'
for path in os.listdir(root_de_data):
    with open(root_de_data + '/' + path, 'rb') as f:
        x = pickle.load(f)
        all_data.append(x)


FileNotFoundError: [Errno 2] No such file or directory: 'raw_data/Large_affective/EEG_Features/DE'

In [ ]:
all_data_array = np.array(all_data)

In [ ]:
all_data_array.shape

In [40]:
import csv

In [15]:
#Labels based on participant ratings
list_valence = []
root = 'dataset/raw_data'
eeg_list = []
root2 = 'dataset/EEG_Features/PSD/'
to_be_iterated = sorted(os.listdir(root))
to_be_iterated.remove('.DS_Store')
for folder, filename in zip(to_be_iterated, sorted(os.listdir(root2))):
    #if folder != '.DS_Store' and filename != '':
    print(folder, filename)
    mat = scipy.io.loadmat(root + '/' + folder + '/' +'After_remarks.mat')
    for movie in range(28):
        movie_number = mat['After_remark'][movie][0][2][0][0]
        ratings = mat['After_remark'][movie][0][0][0][9]
        binary_label = 0
        if ratings > 3.5:
            binary_label = 1
        if movie_number not in [13,14,15,16]:
            list_valence.append([binary_label, movie_number])
        with open(root2 + filename, 'rb') as f:
            if filename =='sub120.pkl.pkl':
                break   
            x = pickle.load(f)
            if movie_number not in [13,14,15,16]:
                x = x[movie]
                x = np.moveaxis(x, -1, 0)
                eeg_list.append(x)
                #print(x.shape)
array_all_valence = np.array(list_valence).astype(np.float32)
eeg_array = np.array(eeg_list)#.astype(np.float32)

sub000 sub000.pkl.pkl
sub001 sub001.pkl.pkl
sub002 sub002.pkl.pkl
sub003 sub003.pkl.pkl
sub004 sub004.pkl.pkl
sub005 sub005.pkl.pkl
sub006 sub006.pkl.pkl
sub007 sub007.pkl.pkl
sub008 sub008.pkl.pkl
sub009 sub009.pkl.pkl
sub010 sub010.pkl.pkl
sub011 sub011.pkl.pkl
sub012 sub012.pkl.pkl
sub013 sub013.pkl.pkl
sub014 sub014.pkl.pkl
sub015 sub015.pkl.pkl
sub016 sub016.pkl.pkl
sub017 sub017.pkl.pkl
sub018 sub018.pkl.pkl
sub019 sub019.pkl.pkl
sub020 sub020.pkl.pkl
sub021 sub021.pkl.pkl
sub022 sub022.pkl.pkl
sub023 sub023.pkl.pkl
sub024 sub024.pkl.pkl
sub025 sub025.pkl.pkl
sub026 sub026.pkl.pkl
sub027 sub027.pkl.pkl
sub028 sub028.pkl.pkl
sub029 sub029.pkl.pkl
sub030 sub030.pkl.pkl
sub031 sub031.pkl.pkl
sub032 sub032.pkl.pkl
sub033 sub033.pkl.pkl
sub034 sub034.pkl.pkl
sub035 sub035.pkl.pkl
sub036 sub036.pkl.pkl
sub037 sub037.pkl.pkl
sub038 sub038.pkl.pkl
sub039 sub039.pkl.pkl
sub040 sub040.pkl.pkl
sub041 sub041.pkl.pkl
sub042 sub042.pkl.pkl
sub043 sub043.pkl.pkl
sub044 sub044.pkl.pkl
sub045 sub

In [16]:
print(eeg_array.shape)
print(array_all_valence.shape)

(2880, 5, 32, 30)
(2880, 2)


In [4]:
#New implementation of labels taking the author's word for it
movie_nums = set()
list_valence = []
root = 'dataset/raw_data'
eeg_list = []
root2 = 'raw_data/Large_affective/EEG_Features/DE/'
to_be_iterated = sorted(os.listdir(root))
to_be_iterated.remove('.DS_Store')
for folder, filename in zip(to_be_iterated, sorted(os.listdir(root2))):
    #if folder != '.DS_Store' and filename != '':
    print(folder, filename)
    mat = scipy.io.loadmat(root + '/' + folder + '/' +'After_remarks.mat')
    for movie in range(28):
        movie_number = mat['After_remark'][movie][0][2][0][0]
        if movie_number not in [13,14,15,16]:
            if movie_number in [1,2,3,4,5,6,7,8,9,10,11,12]:
                list_valence.append(0)
            elif movie_number in [17,18,19,20,21,22,23,24,25,26,27,28]:
                list_valence.append(1)
            else:
                print(movie_number)
        with open(root2 + filename, 'rb') as f:
            if filename =='sub120.pkl.pkl':
                break   
            x = pickle.load(f)
            if movie_number not in [13,14,15,16]:
                x = x[movie]
                x = np.moveaxis(x, -1, 0)
                eeg_list.append(x)
                #print(x.shape)
array_all_valence = np.array(list_valence).astype(np.float32)
eeg_array = np.array(eeg_list).astype(np.float32)

sub000 sub000.pkl.pkl
sub001 sub001.pkl.pkl
sub002 sub002.pkl.pkl
sub003 sub003.pkl.pkl
sub004 sub004.pkl.pkl
sub005 sub005.pkl.pkl
sub006 sub006.pkl.pkl
sub007 sub007.pkl.pkl
sub008 sub008.pkl.pkl
sub009 sub009.pkl.pkl
sub010 sub010.pkl.pkl
sub011 sub011.pkl.pkl
sub012 sub012.pkl.pkl
sub013 sub013.pkl.pkl
sub014 sub014.pkl.pkl
sub015 sub015.pkl.pkl
sub016 sub016.pkl.pkl
sub017 sub017.pkl.pkl
sub018 sub018.pkl.pkl
sub019 sub019.pkl.pkl
sub020 sub020.pkl.pkl
sub021 sub021.pkl.pkl
sub022 sub022.pkl.pkl
sub023 sub023.pkl.pkl
sub024 sub024.pkl.pkl
sub025 sub025.pkl.pkl
sub026 sub026.pkl.pkl
sub027 sub027.pkl.pkl
sub028 sub028.pkl.pkl
sub029 sub029.pkl.pkl
sub030 sub030.pkl.pkl
sub031 sub031.pkl.pkl
sub032 sub032.pkl.pkl
sub033 sub033.pkl.pkl
sub034 sub034.pkl.pkl
sub035 sub035.pkl.pkl
sub036 sub036.pkl.pkl
sub037 sub037.pkl.pkl
sub038 sub038.pkl.pkl
sub039 sub039.pkl.pkl
sub040 sub040.pkl.pkl
sub041 sub041.pkl.pkl
sub042 sub042.pkl.pkl
sub043 sub043.pkl.pkl
sub044 sub044.pkl.pkl
sub045 sub

In [17]:
np.save('eeg_data_no_neutral_DE_channel_first_second_run', eeg_array)
np.save('label_based_on_movie_classification_movie',array_all_valence)

In [7]:
print(array_all_valence)

[0. 0. 0. ... 0. 0. 0.]


In [37]:
a = np.load('eeg_data_no_neutral_DE_channel_first_second_run.npy')
b = np.load('label_based_on_movie_classification.npy')
print(a.shape,b.shape)

(2880, 5, 32, 30) (2880,)


In [21]:
movie_nums

set()

In [43]:
a = np.load('label_valence.npy')

In [12]:
eeg_list = []
root = 'dataset/EEG_Features/DE/'
for filename in sorted(os.listdir(root)):
    print(filename)
    if filename =='sub120.pkl.pkl':
        break
    with open(root + filename, 'rb') as f:
        x = pickle.load(f)
        for movie in x:
            print(movie)
            eeg_list.append(movie)
            break
        


sub000.pkl.pkl
[[[3.37401456 2.20168828 2.28994878 2.70892778 2.7157158 ]
  [2.62442197 2.37617385 2.29018171 2.81616468 2.79221119]
  [3.7806786  2.5477302  2.47723172 2.86656069 2.81487196]
  ...
  [2.34937312 2.56875488 2.01108475 2.97573546 2.93842713]
  [2.71410756 2.62698842 2.40713109 2.8735647  2.63037419]
  [3.9352862  3.18888332 2.55328788 2.9016995  2.61550319]]

 [[3.16960617 2.82644014 2.58838389 3.2282648  3.31850599]
  [2.68054721 2.78100415 2.55099558 3.16322214 3.24654815]
  [2.87753669 2.57446582 2.55375697 3.23828965 3.21389897]
  ...
  [2.55608857 2.83659726 2.1969098  3.17646088 3.32901353]
  [3.0809208  2.75035471 2.64585059 3.23786424 3.1220077 ]
  [3.03131917 3.2548123  2.96233949 3.06539944 3.21561852]]

 [[3.22832083 2.67405009 1.77222489 2.32469381 1.85756288]
  [2.68375364 2.53162332 1.73099634 2.17531154 2.03119739]
  [2.53513069 1.99740816 2.0256369  1.9827243  1.79800758]
  ...
  [2.75961546 2.10723663 1.98161366 2.24432292 2.13927484]
  [2.95823703 2.134

In [59]:
eeg_array = np.array(eeg_list).astype(np.float32)
np.save('eeg_data', eeg_array)

In [52]:
type(np.load('eeg_data.npy')[0][0][0])

numpy.float32

In [60]:
a= np.load('eeg_data.npy')
print(a.shape)

(3360, 32, 30, 5)


In [22]:
df = pd.read_csv('eeg_labels.csv', names = ['valence'])

In [31]:
df.iloc[1]

valence    0.189327
Name: 1, dtype: float64

In [32]:
a = np.load('eeg_data.npy')

In [35]:
a[0].shape

(32, 30)